/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dpozinen

import dpozinen.io.Reader
import kotlin.test.Test

class General {

	@Test
	fun custom() {
		val lines = """

	    """.trimIndent().split("\n")
		val input = Reader(args).read(lines)
		solve(input)
	}

	@Test
	fun general() {
		getFiles(Regex(".*general.*")).forEach { solve(it) }
	}


}
